<a href="https://colab.research.google.com/github/kst577/project-hyperops/blob/main/tp1800.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/DL/Train Set - Train Set.csv')

In [ ]:
df.head()

Region_Name   Month 1   Month 2  ...  Month 70  Month 71  Month 72
0    Region 1  0.154324  0.122901  ...  0.373754  0.333642  0.242176
1    Region 2  0.119708  0.119831  ...  0.344997  0.300503  0.215147
2    Region 3  0.178236  0.165497  ...  0.400269  0.360406  0.335923
3    Region 4  0.225016  0.220602  ...  0.364874  0.311379  0.271102
4    Region 5  0.318976  0.316835  ...  0.416527  0.372523  0.392835

[5 rows x 73 columns]

In [ ]:
df['Region_Name']

0          Region 1
1          Region 2
2          Region 3
3          Region 4
4          Region 5
           ...     
3910    Region 3911
3911    Region 3912
3912    Region 3913
3913    Region 3914
3914    Region 3915
Name: Region_Name, Length: 3915, dtype: object

In [ ]:
df2=df.drop(columns=['Region_Name'])

In [ ]:
X=df2.drop(columns=['Month 72'])

In [ ]:
X

Month 1   Month 2   Month 3  ...  Month 69  Month 70  Month 71
0     0.154324  0.122901  0.127583  ...  0.294693  0.373754  0.333642
1     0.119708  0.119831  0.112970  ...  0.275179  0.344997  0.300503
2     0.178236  0.165497  0.190754  ...  0.296751  0.400269  0.360406
3     0.225016  0.220602  0.224240  ...  0.291502  0.364874  0.311379
4     0.318976  0.316835  0.328486  ...  0.368923  0.416527  0.372523
...        ...       ...       ...  ...       ...       ...       ...
3910  3.400484  3.999567  3.308452  ...  2.472169  3.531807  3.057962
3911  0.374751  0.478654  0.501871  ...  0.604042  0.972735  0.947009
3912  0.463527  0.571315  0.644025  ...  0.737536  1.207824  1.147999
3913  1.641510  1.649937  2.110449  ...  1.123075  1.773948  1.640214
3914  0.307089  0.451604  0.448063  ...  0.546029  0.817059  0.754813

[3915 rows x 71 columns]

In [ ]:
y=df['Month 72']

In [ ]:
import tensorflow as tf

In [ ]:
import keras
import numpy as np

In [ ]:
x=np.array(X)
x.shape

(3915, 71)

In [ ]:
from tensorflow.keras.layers import LSTM,Dropout,Dense,BatchNormalization

In [ ]:
def LSTM_model():
    
    model = keras.models.Sequential()    
    model.add(LSTM(units = 512, return_sequences = True, input_shape = (x.shape[1],1)))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(units = 256, return_sequences = True))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(units = 128, return_sequences = True))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(units = 128, return_sequences = True))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(units = 64, return_sequences = True))
    model.add(Dropout(0.2)) 
    model.add(LSTM(units = 32, return_sequences = True))
    model.add(Dropout(0.2))   
    model.add(LSTM(units = 50))
    model.add(Dropout(0.2))
    model.add(Dense(units=1))
    
    return model

In [ ]:
from keras.callbacks import EarlyStopping


In [ ]:
model = LSTM_model()
model.summary()
model.compile(optimizer='adam', loss='mean_squared_error')   ###

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 71, 256)           264192    
                                                                 
 batch_normalization_2 (Batc  (None, 71, 256)          1024      
 hNormalization)                                                 
                                                                 
 dropout_5 (Dropout)         (None, 71, 256)           0         
                                                                 
 lstm_6 (LSTM)               (None, 71, 128)           197120    
                                                                 
 batch_normalization_3 (Batc  (None, 71, 128)          512       
 hNormalization)                                                 
                                                                 
 dropout_6 (Dropout)         (None, 71, 128)          

In [ ]:
his=model.fit(x,y,epochs=20,batch_size=50)

Epoch 1/20
79/79 [==============================] - 182s 2s/step - loss: 71.7078
Epoch 2/20
79/79 [==============================] - 172s 2s/step - loss: 47.6643
Epoch 3/20
79/79 [==============================] - 175s 2s/step - loss: 38.2780
Epoch 4/20
79/79 [==============================] - 176s 2s/step - loss: 41.4689
Epoch 5/20
79/79 [==============================] - 179s 2s/step - loss: 30.4290
Epoch 6/20
79/79 [==============================] - 178s 2s/step - loss: 25.8002
Epoch 7/20
79/79 [==============================] - 177s 2s/step - loss: 21.4020
Epoch 8/20
79/79 [==============================] - 178s 2s/step - loss: 19.2170
Epoch 9/20
79/79 [==============================] - 178s 2s/step - loss: 16.9888
Epoch 10/20
79/79 [==============================] - 178s 2s/step - loss: 14.8585
Epoch 11/20
79/79 [==============================] - 177s 2s/step - loss: 13.7193
Epoch 12/20
79/79 [==============================] - 178s 2s/step - loss: 12.3955
Epoch 13/20
79/79 [======

In [ ]:
  y_pred=model.predict(x)

In [ ]:

from sklearn import metrics

In [ ]:
mae=metrics.mean_absolute_error(y,y_pred)
mse=metrics.mean_squared_error(y,y_pred)
rmse=np.sqrt(mse)
print(mae)
print(mse)
print(rmse)

1.6621601633962226
9.28145896667605
3.0465486975717373


In [ ]:
X1=df.drop(columns=['Region_Name'])

In [ ]:
X1

Month 1   Month 2   Month 3  ...  Month 70  Month 71  Month 72
0     0.154324  0.122901  0.127583  ...  0.373754  0.333642  0.242176
1     0.119708  0.119831  0.112970  ...  0.344997  0.300503  0.215147
2     0.178236  0.165497  0.190754  ...  0.400269  0.360406  0.335923
3     0.225016  0.220602  0.224240  ...  0.364874  0.311379  0.271102
4     0.318976  0.316835  0.328486  ...  0.416527  0.372523  0.392835
...        ...       ...       ...  ...       ...       ...       ...
3910  3.400484  3.999567  3.308452  ...  3.531807  3.057962  3.118734
3911  0.374751  0.478654  0.501871  ...  0.972735  0.947009  0.806398
3912  0.463527  0.571315  0.644025  ...  1.207824  1.147999  0.768685
3913  1.641510  1.649937  2.110449  ...  1.773948  1.640214  1.489277
3914  0.307089  0.451604  0.448063  ...  0.817059  0.754813  0.542317

[3915 rows x 72 columns]

In [ ]:
x1=np.array(X1.drop(columns=['Month 1']))
x1.shape

(3915, 71)

In [ ]:
m73=model.predict(x1)

In [ ]:
m73

array([[0.12152791],
       [0.12231451],
       [0.12160975],
       ...,
       [0.24717695],
       [1.1945066 ],
       [0.12892461]], dtype=float32)

In [ ]:
d1=X1.drop(columns=['Month 1'])
d1

Month 2   Month 3   Month 4  ...  Month 70  Month 71  Month 72
0     0.122901  0.127583  0.501557  ...  0.373754  0.333642  0.242176
1     0.119831  0.112970  0.326049  ...  0.344997  0.300503  0.215147
2     0.165497  0.190754  0.321733  ...  0.400269  0.360406  0.335923
3     0.220602  0.224240  0.330916  ...  0.364874  0.311379  0.271102
4     0.316835  0.328486  0.483001  ...  0.416527  0.372523  0.392835
...        ...       ...       ...  ...       ...       ...       ...
3910  3.999567  3.308452  2.636698  ...  3.531807  3.057962  3.118734
3911  0.478654  0.501871  0.481275  ...  0.972735  0.947009  0.806398
3912  0.571315  0.644025  0.636814  ...  1.207824  1.147999  0.768685
3913  1.649937  2.110449  1.642345  ...  1.773948  1.640214  1.489277
3914  0.451604  0.448063  0.464692  ...  0.817059  0.754813  0.542317

[3915 rows x 71 columns]

In [ ]:
d1['m73']=m73

In [ ]:
x3=d1.drop(columns=['Month 2'])

In [ ]:
X3=np.array(x3)
X3.shape

(3915, 71)

In [ ]:
m74=model.predict(X3)

In [ ]:
m74

array([[-0.06896526],
       [-0.00645483],
       [-0.05618703],
       ...,
       [-0.12204826],
       [ 0.25373974],
       [-0.11637908]], dtype=float32)

In [ ]:
d1['m74']=m74

In [ ]:
x4=d1.drop(columns=['Month 2',"Month 3"])

In [ ]:
X4=np.array(x4)
X4.shape

(3915, 71)

In [ ]:
m75=model.predict(X4)

In [ ]:
m75

array([[0.11200106],
       [0.10964859],
       [0.1090169 ],
       ...,
       [0.24923372],
       [1.0989952 ],
       [0.13216603]], dtype=float32)

In [ ]:
d1['m75']=m75

In [ ]:
x5=d1.drop(columns=['Month 2',"Month 3","Month 4"])

In [ ]:
X5=np.array(x5)
X5.shape

(3915, 71)

In [ ]:



m76=model.predict(X5)

In [ ]:
m76

array([[0.12207246],
       [0.12136871],
       [0.11607665],
       ...,
       [0.26847094],
       [1.0517155 ],
       [0.1388005 ]], dtype=float32)

In [ ]:
d1['m76']=m76

In [ ]:
x6=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5"])

In [ ]:
X6=np.array(x6)
X6.shape

(3915, 71)

In [ ]:
m77=model.predict(X6)

In [ ]:

m77

array([[0.12101346],
       [0.12115157],
       [0.1199562 ],
       ...,
       [0.26902407],
       [1.0111761 ],
       [0.13910532]], dtype=float32)

In [ ]:
d1['m77']=m77

In [ ]:
x7=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6"])

In [ ]:
X7=np.array(x7)
X7.shape

(3915, 71)

In [ ]:
m78=model.predict(X7)

In [ ]:
m78

array([[0.10643244],
       [0.10975808],
       [0.114721  ],
       ...,
       [0.24649054],
       [0.97881246],
       [0.13629854]], dtype=float32)

In [ ]:
d1['m78']=m78

In [ ]:
x8=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7"])

In [ ]:
X8=np.array(x8)
X8.shape

(3915, 71)

In [ ]:
m79=model.predict(X8)

In [ ]:
m79

array([[0.11457694],
       [0.11615473],
       [0.11387306],
       ...,
       [0.23698616],
       [0.9360646 ],
       [0.13889867]], dtype=float32)

In [ ]:
d1['m79']=m79

In [ ]:
x9=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8"])

In [ ]:
X9=np.array(x9)
X9.shape

(3915, 71)

In [ ]:
m80=model.predict(X9)

In [ ]:
m80

array([[0.11130083],
       [0.11169875],
       [0.1169709 ],
       ...,
       [0.22571862],
       [0.89056545],
       [0.14359033]], dtype=float32)

In [ ]:
d1['m80']=m80

In [ ]:
x10=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9"])

In [ ]:
X10=np.array(x10)
X10.shape

(3915, 71)

In [ ]:
m81=model.predict(X10)

In [ ]:
m81

array([[0.12078214],
       [0.11949337],
       [0.11907524],
       ...,
       [0.21531266],
       [0.84116375],
       [0.1424982 ]], dtype=float32)

In [ ]:
d1['m81']=m81

In [ ]:
x11=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10"])

In [ ]:
X11=np.array(x11)
X11.shape

(3915, 71)

In [ ]:
m82=model.predict(X11)

In [ ]:
m82

array([[0.11580175],
       [0.11623383],
       [0.11683971],
       ...,
       [0.20429367],
       [0.7896029 ],
       [0.13163185]], dtype=float32)

In [ ]:
d1['m82']=m82

In [ ]:
x12=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10","Month 11"])

In [ ]:

X12=np.array(x12)
X12.shape

(3915, 71)

In [ ]:

m83=model.predict(X12)

In [ ]:

m83

array([[0.11957484],
       [0.11615241],
       [0.1168465 ],
       ...,
       [0.19354469],
       [0.7353905 ],
       [0.12988079]], dtype=float32)

In [ ]:
d1['m83']=m83

In [ ]:




x13=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10","Month 11","Month 12"])

In [ ]:
X13=np.array(x13)
X13.shape

(3915, 71)

In [ ]:
m84=model.predict(X13)

In [ ]:

m84

array([[0.11973333],
       [0.11681896],
       [0.11662018],
       ...,
       [0.18324167],
       [0.683075  ],
       [0.12792677]], dtype=float32)

In [ ]:

d1['m84']=m84

In [ ]:
x14=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10","Month 11","Month 12","Month 13"])

In [ ]:
X14=np.array(x14)
X14.shape

(3915, 71)

In [ ]:
m85=model.predict(X14)

In [ ]:
m85

array([[0.12010938],
       [0.11596423],
       [0.11591971],
       ...,
       [0.17533553],
       [0.62976646],
       [0.1273737 ]], dtype=float32)

In [ ]:

d1['m85']=m85

In [ ]:


x15=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10","Month 11","Month 12","Month 13","Month 14"])

In [ ]:
X15=np.array(x15)
X15.shape

(3915, 71)

In [ ]:
m86=model.predict(X15)

In [ ]:
m86

array([[0.12010765],
       [0.11850286],
       [0.11725748],
       ...,
       [0.17215693],
       [0.577271  ],
       [0.1301145 ]], dtype=float32)

In [ ]:
d1['m86']=m86

In [ ]:
x16=d1.drop(columns=['Month 2',"Month 3","Month 4","Month 5","Month 6","Month 7","Month 8","Month 9","Month 10","Month 11","Month 12","Month 13","Month 14","Month 15"])

In [ ]:
X16=np.array(x16)
X16.shape

(3915, 71)

In [ ]:
m87=model.predict(X16)

In [ ]:
m87

array([[0.11344165],
       [0.11340135],
       [0.12103534],
       ...,
       [0.17254776],
       [0.5248574 ],
       [0.14035922]], dtype=float32)

In [ ]:
d1['m87']=m87

In [ ]:
d1

Month 2   Month 3   Month 4  ...       m85       m86       m87
0     0.122901  0.127583  0.501557  ...  0.120109  0.120108  0.113442
1     0.119831  0.112970  0.326049  ...  0.115964  0.118503  0.113401
2     0.165497  0.190754  0.321733  ...  0.115920  0.117257  0.121035
3     0.220602  0.224240  0.330916  ...  0.117175  0.117490  0.118561
4     0.316835  0.328486  0.483001  ...  0.116736  0.116357  0.116815
...        ...       ...       ...  ...       ...       ...       ...
3910  3.999567  3.308452  2.636698  ...  2.106608  2.057045  2.014003
3911  0.478654  0.501871  0.481275  ...  0.136586  0.135897  0.137557
3912  0.571315  0.644025  0.636814  ...  0.175336  0.172157  0.172548
3913  1.649937  2.110449  1.642345  ...  0.629766  0.577271  0.524857
3914  0.451604  0.448063  0.464692  ...  0.127374  0.130114  0.140359

[3915 rows x 86 columns]

In [ ]:
from google.colab import files
d1.to_excel('25nov.xlsx') 
files.download('25nov.xlsx')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>